import Head from 'next/head';
import { GetServerSideProps } from 'next';
import SearchBar from '../components/SearchBar/SearchBar';
import SearchResults from '@/components/SearchResults/SearchResults';
import { IPData } from '../types/ipData';
import { useState, FC, useMemo } from 'react';
import dynamic from 'next/dynamic';
// import Map from '@/components/Map/Map';

type Props = {
  ipData: IPData;
};

const Home: FC<Props> = (props: Props) => {
  const [ipData, setIpData] = useState(props.ipData);
  const [lat, setLat] = useState(props.ipData.lat)
  const [lng, setLng] = useState(props.ipData.lng)

  const searchIP = async (ip: string) => {
    console.log(ip);
    const res = await fetch(
      `https://geo.ipify.org/api/v2/country,city?apiKey=at_jYSorhvdElfbm0E3FJvgq3ZEN1OTs&ipAddress=${ip}`
    );
    const data = await res.json();

    const ipData: IPData = {
      address: data.ip,
      location: `${data.location.city}, ${data.location.country} ${data.location.postalCode}`,
      timezone: `UTC ${data.location.timezone}`,
      isp: data.isp,
      lat: data.location.lat,
      lng: data.location.lng
    };

    setLat(data.location.lat)
    setLng(data.location.lng);

    console.log(ipData);

    setIpData(ipData);
  };

  const Map = useMemo(() => dynamic(
    () => import("@/components/Map/Map"), // replace '@components/map' with your component's location
    { 
      loading: () => <p>A map is loading</p>,
      ssr: false // This line is important. It's what prevents server-side render
    }
  ), [/* list variables which should trigger a re-render here */])

  return (
    <>
      <Head>
        <title>Frontend Mentor | IP Address Tracker</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon-32x32.png' />
      </Head>
      <main className='h-screen flex flex-col'>
        <div className="flex flex-col items-center bg-[url('/pattern-bg.png')] h-56 bg-cover px-32 relative">
          <h1 className='text-white text-2xl py-6 font-semibold'>
            IP Address Tracker
          </h1>
          <SearchBar onSearch={searchIP}></SearchBar>
          <SearchResults ipData={ipData}></SearchResults>
        </div>

        <Map className='w-full flex-1 z-0' lat={lat} lng={lng} ></Map>
      </main>
    </>
  );
};

// / This gets called on every request
export const getServerSideProps: GetServerSideProps<Props> = async () => {
  // Fetch data from external API
  const res = await fetch(`https://geo.ipify.org/api/v2/country,city?apiKey=at_jYSorhvdElfbm0E3FJvgq3ZEN1OTs`)
  const data = await res.json()

  const ipData: IPData = {
    address: data.ip,
    location: `${data.location.city}, ${data.location.country} ${data.location.postalCode}`,
    timezone: `UTC ${data.location.timezone}`,
    isp: data.isp,
    lat: data.location.lat,
    lng: data.location.lng
  };

  return { props: { ipData } };
};

export default Home;
